# === Data ===
train_jsonl: "/project/biocomplexity/gza5dr/CAFO_Test/Final Experiments/splits/CAFOSat_fold_0_train.jsonl"
test_jsonl: "/project/biocomplexity/gza5dr/CAFO_Test/Final Experiments/splits/CAFOSat_fold_0_test.jsonl"
num_classes: 5
data_type: CAFOSat_fold_0_train

# === Model ===
model_name: remoteclip  # Options: resnet18, resnet50, vit_b_16, swin_b, efficientnet_b0, efficientnet_b3, dinov2_vit_b, convnext_tiny

# === Training Parameters ===
batch_size: 8
lr: 0.0001
max_epochs: 1
patience: 3
precision: bf16-mixed
worker: 4

# === Logging and Runtime ===
log_dir: logs/new_run/
gpus: 4