# === Data ===
train_jsonl: "/project/biocomplexity/gza5dr/CAFO_Test/Final Experiments/splits/CAFOSat_overall_train.jsonl"
test_jsonl: "/project/biocomplexity/gza5dr/CAFO_Test/Final Experiments/splits/CAFOSat_overall_test.jsonl"
num_classes: 5
data_type: CAFOSat_fold_overall_train_ablation
size: 720
ckpt_path: "/project/biocomplexity/wyr6fx(Nibir)/checkpoints/models--chendelong--RemoteCLIP/snapshots/bf1d8a3ccf2ddbf7c875705e46373bfe542bce38/RemoteCLIP-ViT-B-32.pt"

# === Model ===
model_name: efficientnet_b0  # Options: resnet18, resnet50, vit_b_16, swin_b, efficientnet_b0, efficientnet_b3, dinov2_vit_b, convnext_tiny
use_attn_mask: False ### always false
use_spatial_attn: False ## keep it true
use_attn_pooling: True ### use use_attn_pooling or use_conf_gap or  use_component_pool or none
use_evidence_map: False ### always true
use_component_pool: False
use_conf_gap: False
use_concepts: False
use_rel_feats: False
linear_head: False
freeze_model: False
deepsets_hidden: 256
# === Training Parameters ===
batch_size: 4
lr: 0.0001
max_epochs: 10
patience: 10
precision: bf16-mixed
worker: 4

# === Logging and Runtime ===
log_dir: MODEL_Results/logs/
gpus: 4