# === Data ===
train_jsonl: "/project/biocomplexity/gza5dr/CAFO_Test/Final Experiments/splits/CAFOSat_overall_train.jsonl"
test_jsonl: "/project/biocomplexity/gza5dr/CAFO_Test/Final Experiments/splits/CAFOSat_overall_test.jsonl"
num_classes: 5
data_type: CAFOSat_fold_overall_train_epoch_30_mask_new_test_pool_spatial_swin_v2_wpool_new
size: 720
ckpt_path: "/project/biocomplexity/wyr6fx(Nibir)/checkpoints/models--chendelong--RemoteCLIP/snapshots/bf1d8a3ccf2ddbf7c875705e46373bfe542bce38/RemoteCLIP-ViT-B-32.pt"

# === Model ===
model_name: swin_b  # Options: resnet18, resnet50, vit_b_16, swin_b, efficientnet_b0, efficientnet_b3, dinov2_vit_b, convnext_tiny
use_attn_mask: False
use_spatial_attn: True
use_attn_pooling: True
# === Training Parameters ===
batch_size: 4
lr: 0.0001
max_epochs: 20
patience: 5
precision: bf16-mixed
worker: 4

# === Logging and Runtime ===
log_dir: logs/new_run/
gpus: 4